### ISSUE TITLE
Unknown writer: gfm

### ISSUE THREAD

**Issue by privefl** [ColinFay/jekyllthat#2]
Add the end of the knitting process, I get: 
```
pandoc: Unknown writer: gfm
Erreur : pandoc document conversion failed with error 9
```

What I'm trying to convert: https://github.com/privefl/blog/blob/gh-pages/_posts/test-jekyllthat.Rmd

**Comment by ColinFay** [comment]
This might be due to your Pandoc version, thanks for pointing this out. 

`gfm` stands for "GitHub Flavored Markdown", and is a modern version of `github_document`. 

I've just pushed a bug fix, inspired from 
https://github.com/rstudio/rmarkdown/blob/master/R/github_document.R 
to handle this. 

Can you please reinstall the package and let me know ?

**Comment by privefl** [comment]
I can now Knit.

**Comment by ColinFay** [comment]
Nice. Thanks for reporting this bug!
